### ISSUE TITLE
[Feature] Documentation: Migration guide from 1.x

### ISSUE THREAD

**Issue by ryantheleach** [Draycia/Chat#178]
There should be a wiki page outlining the changes from version 1.x, and what changes need to be made to be compatible.

I attempted to copy my (inactive) settings from my 1.15 server to my 1.18 server running CarbonChat 2.0

I found that the permissions structure had changed from:

![image](https://user-images.githubusercontent.com/141554/146590613-8db9a2c5-a85f-41d7-bf5b-5640f3054cdf.png)

what was listed on the wiki as:

carbon.Global
carbon.Global.speak

So I booted up the luckperms editor, and compared it to the Wiki entry that was updated 6 days ago.

I've listed them below for reference, if someone in the know can update the wiki (if appropriate) or the default suggestions that Carbon registers with luckperms (presumably through its plugin.yml)

-----

## **Listed on wiki, but do not appear in luckperms suggestions**:

`carbon.<channelname>`
`carbon.<channelname>.speak`
`carbon.clearchat.exempt`

`carbon.ignore.exempt`

`carbon.mute.exempt`
`carbon.mute.notify`

`carbon.nickname.others`
`carbon.nickname.see`
`carbon.nickname.self`
`carbon.nickname.set`

`carbon.whisper.vanished`

## **Missing from wiki, but listed in Luck Perms suggestion list**:
`carbon`
`carbon.nickname`
`carbon.reload`
`carbon.channel`
`carbon.channel.global`
`carbon.clearchat`
`carbon.whisper.message`

**Comment by Draycia** [comment]
Changed whisper permission to `carbon.whisper` from `carbon.whisper.message` in 90843e084c225c57bca9a6f8d4cd5eb2d5b79e23

All other permissions are now listed in the wiki.
All permissions and sub-permissions should be registered for luckperms now.

I don't have much time nor the plans to write a migration guide, very few people used v1.
Migration should be as simple as backing up old configs, generating new ones, and copying over settings as necessary.
