### ISSUE TITLE
[Bug] Japanese files are garbled.

### ISSUE THREAD

**Issue by NamiUni** [Draycia/Chat#180]
## Bug Description:
Japanese language are garbled and do not display properly.

### What is not working as it should?
Messages-ja_JP.properties in the locale folder is garbled.

### Steps to reproduce:
1. Install Carbon, Vault, andLuckPerms

### System Details:
This server is running Purpur version git-Purpur-1445 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8183257 on HEAD)
You are running the latest version
Previous version: git-Paper-68 (MC: 1.18.1)

1. Server Type: Paper         
2. Server Software: git-Paper-68  
3. MC Version: 1.18.1          
4. Carbon Version: 2.0.4 build25

### Pastebins:
https://pastebin.com/ZH4f5274

**Comment by jpenilla** [comment]
Are you saving the file with UTF-8 encoding?

**Comment by NamiUni** [comment]
Yes, of course.
The Japanese language file that is automatically generated when Carbon is installed is already garbled.
However, I just took a peek at the contents of the CarbonChat jar file and found a language file that was not garbled. That's odd.
I copied that file and placed it in the local directory, and now Japanese is displayed normally.

**Comment by jpenilla** [comment]
Thanks for the detailed report, should be fixed now.

**Comment by NamiUni** [comment]
Thank you for fixing the bug too 😘
