### ISSUE TITLE
[Feature] Add multi line support for formats

### ISSUE THREAD

**Issue by BlitzOffline** [Draycia/Chat#189]
### Proposed Feature Description:

I would love to see formats accept a list of strings.This would be really really helpful on maintaining and managing a format. This is how my format looks with word wrap turned on: https://imgur.com/WLftrE6.

### Proposed Feature Functionality:

Basically each format would be a list of strings instead of strings (or maybe it can be both, and you can decide which to use. this would also maintain backwards compatibility I guess) and it would literally just concatenate those strings into one. It would look something like this in config: https://imgur.com/OHwlcXZ but the actual chat message would be just 1 line.

**Comment by Draycia** [comment]
Already a feature in HOCON:
<https://github.com/lightbend/config/blob/master/HOCON.md#string-value-concatenation>
<https://getakka.net/articles/configuration/hocon.html#duplicate-keys-and-object-merging>
Simply duplicate the format key and the values will concatenate.
Example:
```hocon
thing {
  staff-format="<red>thing here"
  staff-format="<blue>another thing here"
  staff-format="<green>all of these will concatenate into a single string!"
}```
