### ISSUE TITLE
[Feature] Ability for players to use tags in their messages

### ISSUE THREAD

**Issue by BlitzOffline** [Draycia/Chat#190]
### Proposed Feature Description:

I would love for players to be able to use tags like <yellow> in their message and they would be parsed. so if my message color normally is `<gray><message>` but the player sends a message like `<gradient:#5e4fa2:#f79459> Hello There!` it would send the message with the gradient tag parsed.

### Proposed Feature Functionality:

As explained above, this would parse mini message tags sent in player messages. It would be nice if they were permission based or something (tho that sounds like a lot of complication).

**Comment by soup6020** [comment]
Even just a permission for all tags would probably be sufficient, I can't imagine a scenario where I'd allow players to use one but not others.

**Comment by Draycia** [comment]
Forgot to close this issue, this is already implemented in the 2.1 branch, with a separate permission for each tag.
Working on providing 2.1 snapshots or a release for it soon.
