### ISSUE TITLE
[Feature] Pass messages from proxy to backend

### ISSUE THREAD

**Issue by Prof-Bloodstone** [Draycia/Chat#191]
### Proposed Feature Description:

Ability for backend plugins to react to player messages, when proxy version of CarbonChat is used

### Proposed Feature Functionality:

Instead if denying the player messages on proxy level, they should be passed down to the backend.

At least having the proxy send the message just for "informational" purposes (i.e. MC->Discord bridge) would be a great improvement,
but having some sort of (configurable?) interop with backend would be nice (i.e. let backend cancel the message) could also be useful.

**Comment by Draycia** [comment]
We have decided not to have a bridge between the proxy and the backend, at that point it's better to find a velocity discord bridge or use the plugin on all backend servers instead of the proxy
