### ISSUE TITLE
[Bug] crash if create new locale plugin!

### ISSUE THREAD

**Issue by TOWUK** [Draycia/Chat#192]
## Bug Description:
if you create a new translation localization file, for example **messages-ru_RU.properties** and put in the plugin configuration **default-locale="ru_RU"** then the plugin will not run and will write an error to the console!

### What is not working as it should?
doesn't start when server/proxy starts

### Steps to reproduce:
I personally did this:
copied **messages-en_US.properties** file and renamed to **messages-ru_RU.properties**
then in config **default-locale="en_US"** changed to **default-locale="ru_RU"**

### System Details:

1. Server Type:          BUKKIT and PROXY
2. Server Software:      PAPERMC latest and VELOCITY latest
3. MC Version:           1.18.1+
4. Carbon Version:       latest build jenkins

### Pastebins:

config
https://pastebin.com/Nxehkze4

### Any other relevant details:

log start server (bukkit or proxy)
https://pastebin.com/B3L4kxmz

**Comment by underscore11code** [comment]
~~Looks like an issue with the Russian translations. If that's a translation file you created, it appears one of the translation keys doesn't exist.~~

Disregard.

**Comment by underscore11code** [comment]
Scratch the above, Vic has informed me that even if that is the case, there shouldn't be an issue.

**Comment by TOWUK** [comment]
> Сотрите вышеизложенное, Вик сообщил мне, что даже если это так, проблем быть не должно.

i just copy file and rename! not change file data!

**Comment by TOWUK** [comment]
> ~Looks like an issue with the Russian translations. If that's a translation file you created, it appears one of the translation keys doesn't exist.~
> 
> Disregard.

if i just ignore, plugin not loaded on velocity

**Comment by Draycia** [comment]
fixed in 6f0cce3
