### ISSUE TITLE
[Bug] (Velocity) Compatibility issue with moderation plugins

### ISSUE THREAD

**Issue by 4drian3d** [Draycia/Chat#208]
## Bug Description:
Currently Carbon (Velocity) uses the original message given by the PlayerChatEvent event instead of the message modified by plugins https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/player/PlayerChatEvent.ChatResult.html#getMessage() in its ChatListener https://github.com/Hexaoxide/Carbon/blob/2.1/velocity/src/main/java/net/draycia/carbon/velocity/listeners/VelocityChatListener.java#L82 making plugins that modify messages incompatible since the original message will always be sent

### What is not working as it should?
The message sent will always be the original one no matter if some plugin with a higher priority modifies it

### Steps to reproduce:

1. Install Carbon together with a plugin that modifies chat messages, for example ChatRegulator
2. Write something in the chat
3. The message sent by Carbon will be the original message given by the PlayerChatEvent without any modification

### System Details:

1. Server Type: Velocity 
2. Server Software: Velocity 3.0.2 SNAPSHOT   

### Any other relevant details:

https://github.com/4drian3d/ChatRegulator/issues/27

**Comment by SenPr** [comment]
I think this might be intended to support signed chat and chat preview in the future. Though I'm not sure.

**Comment by Draycia** [comment]
@SenPr I'm still waiting for signed chat API / support in Velocity, but this is still a bug worth fixing in the meantime.
