### ISSUE TITLE
[Bug] Pinging players not working for all players

### ISSUE THREAD

**Issue by Olzie-12** [Draycia/Chat#220]
## Bug Description:
For some reason pinging doesn't work properly, it only works if you ping yourself

### What is not working as it should?
It should allow you to be able to ping any other player apart from yourself, I mean what's the point of pinging yourself. 
From what the could looks like it does check for all the recipients but isn't working.
### Steps to reproduce:
1. Install Carbon, Vault, and LuckPerms
2. Try pinging another player on the server, it doesn't work. If you ping yourself, it does work.

### System Details:

1. Server Type:          Petal/Pufferfish
2. Server Software:    Current: git-petal-"cc713c0" (MC: 1.19.2)*
3. MC Version:            1.19.2
4. Carbon Version:

**Comment by Olzie-12** [comment]
The issue is because recipient in the channel renderer is always the sender.

**Comment by Olzie-12** [comment]
Fixed in #222

**Comment by Draycia** [comment]
> The issue is because recipient in the channel renderer is always the sender.

This should be fixed as of a45ae78f22022543733c965708b72d0523453573
The decorate event is no longer used, and the recipients are now passed into the renderer.
