### ISSUE TITLE
[Bug] Plugin enabling error (dependency issue?)

### ISSUE THREAD

**Issue by Olzie-12** [Draycia/Chat#224]
## Bug Description:

When the plugin tries to enable an error is thrown and then automatically disables
### What is not working as it should?
The plugin should enable and not throw any errors.
### Steps to reproduce:

1. Install Carbon, Vault, and LuckPerms

### System Details:

1. Server Type: Petal
2. Server Software git-petal-"cc713c0" (MC: 1.19.2)*
3. MC Version: 1.19.2
4. Carbon Version: The latest commit

### Pastebins:
When loading: https://pastebin.com/XwwhPpdd

**Comment by Draycia** [comment]
I had the same issue in the past when trying to use Sound objects in the config. My solution was to use this instead of the Sound.

```java
    private boolean playSound = false;
    private Key name = Key.key("block.anvil.use");
    private Sound.Source source = Sound.Source.MASTER;
    private float volume = 1.0f; // 0.0 -> infinity
    private float pitch = 1.0f; // 0.0 -> 2.0

    public Sound sound() {
        return Sound.sound(this.name, this.source, this.volume, this.pitch);
    }
```

I'll see why this is happening and probably write a Sound serializer soon.

**Comment by Draycia** [comment]
As of commit 4a53bc85b55edcd0e56586970176bd99b1de9f1a, plugin no longer supports 1.19.2
Commit 032b392c6b6f146842e159a5c75514cee8e524bc supports and runs on 1.19.3
