### ISSUE TITLE
[Feature] Parity with VentureChat in terms of features

### ISSUE THREAD

**Issue by Technofied** [Draycia/Chat#227]
### Proposed Feature Description:

We add remaining features to close the gap between Carbon and VentureChat. :)

### Proposed Feature Functionality:

- [x] Proxy muting: You can mute players on any server in the network through the bungeecord proxy.
- [ ] Channel cooldowns: You can set a cooldown time in seconds for a channel for a cooldown between a player sending a message. There is a bypass permission for cooldowns.
- [ ] Towny and Factions channels: You can create special channels for Towny, Nation, and Factions. Check the config for more details!
- [ ] Logging changes. Support for logging to MySQL or to separate files?

**Comment by Technofied** [comment]
I did not include message forcing as that's something you can do with /sudo, as well as BungeeCord jazz since we're only on Velocity.

**Comment by underscore11code** [comment]
Personally I think MySQL logging is out of scope. For commands, just use CoreProtect or friends. CP & friends can also do chat, although I suppose it can't really log channels so I suppose maybe logging chat could be ok.

*While on the topic, if we do add chat logging, make sure to not have an SQL injection vuln ;)*

**Comment by VQ9** [comment]
With party chat and factions channels, I would prefer a generalised system which any plugin can hook into. Perhaps a more generalised permissions based channel system which is per-user / per suffix.

**e.g carbon.channel.factions.{faction_name}**. The suffix would be a sort of subchannel of sorts. 
**e.g carbon.channel.party.{player_name}**. For a customisable approach to a party system. Then a 3rd party addon simply has to give the carbon.channel.party.{player_name} permission for access to a party subchannel.

**Comment by Draycia** [comment]
Closed in favor of the referenced issues
