### ISSUE TITLE
[Feature] Send channel messages from console

### ISSUE THREAD

**Issue by Folas1337** [Draycia/Chat#242]
### Proposed Feature Description:

I would love to be able to send messages from the console to certain channels, just like I can as a player in game.
Using the command `ch global testMessage` or like this when written with variables: `ch <channel> <message>` would be quite helpful, especially in a use case I have where I'd like to send a message to a specific channel when people join and leave the network.

My use case looks like this: Whenever someone joins, I want to send a message in a channel I'll call joinLeave which people can not send messages to but read messages that are announced there. Then I will install a plugin like RocketJoin on the proxy, which executes a command whenever someone joins or leaves the network/proxy. Then through the use of https://github.com/Phoenix616/ConnectorPlugin I can simply send a command from the proxy to a backend server which then executes the command mentioned above, basically sending `ch global %player_name% has joined the network` or `ch global %player_name% has left the network`.

I was alternatively thinking of the player themselves saying this/forcing them to execute the command **but** I'm afraid if I did, they could send any random messages into this channel which is not desirable so I came up with this solution.

I'd greatly appreciate it being added some time soon :)

**Comment by Draycia** [comment]
https://github.com/Hexaoxide/Carbon/pull/245
