### ISSUE TITLE
[Bug] mySQL needs some work/love :)

### ISSUE THREAD

**Issue by Folas1337** [Draycia/Chat#243]
## Bug Description:
I've brought this up in the Discord before but I don't want it to get lost, so I thought I'd open a GitHub issue on it as well.
When using mySQL as a storage type and then switching from one server to another, it doesn't seem to apply when you ignored someone, left a channel or similar actions.

### What is not working as it should?
The storage type mySQL as described above.

### Steps to reproduce:
1. Install Carbon, Vault, and LuckPerms, set up mySQL and redis servers
2. Hook up carbon to both redis and mysql and install on 2 backend servers (called serverA and serverB)
3. Ignore personA on serverA and move to serverB
4. Notice how personA's messages are not ignored

### System Details:
1. Server Type:          Paper
2. Server Software:    Paper-524 (MC: 1.19.4)
5. MC Version:           1.19.4
6. Carbon Version:     2.1.0 Snapshot (build 1035)

_I hope this hasn't been fixed in the meantime cause I didn't really test it again with this latest build, I'm mostly assuming that the old bugs are still around that we discussed on the Discord a while ago._

**Comment by jpenilla** [comment]
This issue wasn't confirmed to still exist at the time it was opened, and at this point is quite old. Please open a new issue for any problems tested to be present on the latest beta
