### ISSUE TITLE
[Feature] Regex filtering

### ISSUE THREAD

**Issue by Potothingi** [Draycia/Chat#248]
### Proposed Feature Description:

I want to filter profanity with a regular expression.

### Proposed Feature Functionality:

Add regular expression filtering

**Comment by 4drian3d** [comment]
Carbon is just a chat plugin, to regulate chat violations you can use [ChatRegulator](https://modrinth.com/plugin/chatregulator) in Velocity or ChatSentinel in Paper.
Same with #249

**Comment by Draycia** [comment]
89894fad30acfa8ccd1e0ac5ff7e4b85b069527f
