### ISSUE TITLE
[Bug] Registered channels shouldn't be a WARN but an INFO

### ISSUE THREAD

**Issue by Folas1337** [Draycia/Chat#256]
## Bug Description:
Logs say this:
`[16:04:16] [Server thread/WARN]: [CarbonChat] Registered channels: [carbon:global]`
which I think should instead be this:
`[16:04:16] [Server thread/INFO]: [CarbonChat] Registered channels: [carbon:global]`

Don't you think? I don't see anything worth being a warning when it's just registering channels as it should? Nothing major obviously but a really small thing that might be worth fixing ;)

### System Details:
1. Server Type:          Paper
2. Server Software:    Paper version git-Paper-58 (MC: 1.20.1)
3. MC Version:           1.20.1
4. Carbon Version:     2.1.0-beta.14

**Comment by Draycia** [comment]
f7e79d0f67babe46cd6ab5cea7a58f48104f7c8f
