### ISSUE TITLE
[Feature] EZColors compatibility (Legacy compatibility) and PAPI additions

### ISSUE THREAD

**Issue by supertakeru** [Draycia/Chat#261]
### Proposed Feature Description:

1. Legacy Compatibility, especially for plugins such as EZColors. This is because when you use %ezcolors_color% with a default color it would return something like <&6> which does not get properly translated into color.

2. PAPI addition for nicknames: You have the feature in your plugin, it should be a placeholder that can be used.

### Proposed Feature Functionality:

1. Function - Plugin would be able to translate legacy color codes correctly

2. Function - Plugin has nickname placeholder that is able to be used by other plugins properly.

**Comment by Draycia** [comment]
33e19541e00a891169d449a4ac95d2b608974181
In case anyone sees this in the future: Legacy section symbols are supported but ampersand isn't.
To fix this, wrap legacy ampersand placeholders in [Kyorify](https://api.extendedclip.com/expansions/kyorify/).
