### ISSUE TITLE
[Feature] Group/Party Chat

### ISSUE THREAD

**Issue by supertakeru** [Draycia/Chat#266]
### Proposed Feature Description:

Ability for players to create their own private party/group chat

### Proposed Feature Functionality:

Player can create a chat using commands, for example:

Player uses "/party create *Party Name*"
Player invites friends using "/party invite *User/Display name*"
Player is able to use the private group chat using "/party chat"

**Comment by RealTriassic** [comment]
> Player is able to use the private group chat using "/party chat"

It'd be cool if there was an option to have parties be a channel instead

**Comment by jpenilla** [comment]
Would players be able to join more than one party at a time?

**Comment by RealTriassic** [comment]
> Would players be able to join more than one party at a time?

Typically in other party plugins, players can only be in one party at a time, so I guess it should be the same here, or maybe have a configuration option for it if you'd like

**Comment by RealTriassic** [comment]
Also, not sure if this is out of scope for this project, but it'd be really cool if while a player is in a party, it could display a scoreboard for the players in the party that displays which players are online or offline, who's the party's leader/admin (person who has permission to add players to the party), etc

**Comment by Draycia** [comment]
> Also, not sure if this is out of scope for this project, but it'd be really cool if while a player is in a party, it could display a scoreboard for the players in the party that displays which players are online or offline, who's the party's leader/admin (person who has permission to add players to the party), etc

Scoreboards are probably out of scope. We could provide placeholders for that info, however.

**Comment by RealTriassic** [comment]
> > Also, not sure if this is out of scope for this project, but it'd be really cool if while a player is in a party, it could display a scoreboard for the players in the party that displays which players are online or offline, who's the party's leader/admin (person who has permission to add players to the party), etc
> 
> Scoreboards are probably out of scope. We could provide placeholders for that info, however.

As long as there's an API for parties, that's alright for me
