### ISSUE TITLE
[Bug] /whisper overrides EssentialsX but /msg does not display the same behavior

### ISSUE THREAD

**Issue by ChiboYen** [Draycia/Chat#271]
## Bug Description:
/whisper tab completion works but /msg does not for players who are not OP when using essentialsX.

### What is not working as it should?
The /msg command seems to not be replacing the EssentialsX /msg command completely in terms of tab completion: it does not behave the same way that /whisper does currently.

### Steps to reproduce:
Plugins: Carbon, Vault, Luckperms, EssentialsX.

Doesn't matter channel configuration, it's /msg and /whisper.

On a player with only carbonchat whisper permissions, use /whisper and tab complete works, /msg and it does not (since it somehow still uses essentialsX /msg tab completion)

### System Details:

Purpur-2023 1.20.1
Carbon 2.1.0-beta-17

**Comment by jpenilla** [comment]
You can adjust command labels and aliases in command-settings.conf. The main label will override other plugins (i.e. the last plugin to register it in the load order wins) but aliases will not. You could also ask the EssX devs if there is a way to disable EssX commands through their config.

**Comment by ChiboYen** [comment]
Okay thank you for the response. I will probably have to turn to commands.yml for this, I appreciate it!
