### ISSUE TITLE
[Bug] Server Crash on join 1.20.1

### ISSUE THREAD

**Issue by phrogwrld** [Draycia/Chat#274]
## Bug Description:

Upon loading the Carbon mod (v2.1.0-beta.18) and attempting to join the server, a crash occurs as soon as a player joins. This issue is consistent and has also been observed with the previous version (v2.1.0-beta.17) of the mod.

### What is not working as it should?

Upon player join, the server crashes, rendering it inaccessible.

### System Details:

1. Server Type:          Fabric
2. Server Software:   
3. MC Version:          1.20
4. Carbon Version:	 2.1.0-beta.18

### Pastebins:

The crash report can be found at this [Pastebin Link](https://pastebin.com/RqAB8WaP).

**Comment by jpenilla** [comment]
This is a similar mod conflict to what happened at https://github.com/jpenilla/better-fabric-console/issues/27, Carbon isn't at fault here.
