### ISSUE TITLE
[Feature] Channels for other plugins

### ISSUE THREAD

**Issue by Draycia** [Draycia/Chat#283]
Moved from #227 
Add support / channels for the following plugins:
- [x] Towny
  - [x] Nation
  - [x] Town
- [ ] FactionsUUID
  - [ ] Alliance
  - [ ] Faction
  - [ ] Truce?
- [x] mcMMO
  - [x] Party

**Comment by SrBedrock** [comment]
Suggestion: party chat from the mcMMO plugin

**Comment by Folas1337** [comment]
Oh lord I'd love to see towny being supported! Just in case you were wondering if anyone was interested in this at all :)
