### ISSUE TITLE
[Feature] Nickname Blacklist

### ISSUE THREAD

**Issue by NamiUni** [Draycia/Chat#294]
### Proposed Feature Description:
Add blacklist to nicknames.
Currently, nicknames can be set freely, but it is possible to impersonate a celebrity or an admin.
We need a blacklist to prevent arbitrary names or already existing player names from being set.

~~It would also be better if it could be confirmed in the chat section that the name displayed is a nickname. For example, displaying the original name in hover text.~~
Better Solutions #295 

### Proposed Feature Functionality:
- Adding a Blacklist
~~- nickname hovertext~~

**Comment by NamiUni** [comment]
#295 makes more sense, so I'll close it.

**Comment by jpenilla** [comment]
I think having both would be good.

We could have a regex block list and also possibly an event for other plugins to block nicknames on whatever criteria they want.

**Comment by Draycia** [comment]
https://github.com/Hexaoxide/Carbon/pull/360
