### ISSUE TITLE
[Bug] On shutdown or randomly starts failing

### ISSUE THREAD

**Issue by shadow2hel** [Draycia/Chat#297]
### What is not working as it should?
On shutdown or randomly it will start spewing the error causing the server to hold indefinitely.

### Steps to reproduce:
1. Install Carbon, and LuckPerms
2. Shutdown the server

### System Details:

1. Server Type:           Fabric
2. Server Software:    Fabric 0.14.22
3. MC Version:           1.20.1
4. Carbon Version:     2.1.0-beta.20

### Pastebins:
config: https://pastebin.com/L3hJ3BEF
log: https://pastebin.com/vt7HX0Kc

**Comment by jpenilla** [comment]
Fixed in beta 21, the release is currently building

**Comment by jpenilla** [comment]
https://github.com/Hexaoxide/Carbon/releases/download/v2.1.0-beta.21/carbonchat-fabric-2.1.0-beta.21.jar

**Comment by shadow2hel** [comment]
Wow that was fast, thank you!
