### ISSUE TITLE
[Feature] Clicking on PM suggests the command

### ISSUE THREAD

**Issue by Folas1337** [Draycia/Chat#312]
### Proposed Feature Description:

I'm taking inspiration from the plugin Party and Friends for this one but I liked it quite a lot.
Basically when you click on a PM you are having with someone, it fills in the command `/msg <username> ` so you can then just start typing the message you wanna send to them.

### Proposed Feature Functionality:

Often times you are having conversations with several people and when using `/r <msg>` it will potentially go to the wrong person. That's why I found it quite useful that you could simply click on a message you had with someone and it would fill out the message command for you and you could just type out your message you wanted to send to them.

I don't know the exact jargon for this feature in Minecraft where it basically fills out a command for you but doesn't send it but that's what I'm looking for.

If you need me to clarify anything, feel free to reply :)

**Comment by jpenilla** [comment]
`<click:suggest_command:'/whisper <sender_username> '>lorem ipsum`

**Comment by Folas1337** [comment]
> `<click:suggest_command:'/whisper <sender_username> '>lorem ipsum`

Oh right that's a thing, sorry to have bothered you :D

**Comment by jpenilla** [comment]
The username placeholders are new in the closing commit. We're still considering whether we want to add this to the default locale.
