### ISSUE TITLE
[Feature] Integration with BlockBot

### ISSUE THREAD

**Issue by SerpentesNL** [Draycia/Chat#348]
### Proposed Feature Description:

Not sure if the integration has to come from Carbon or from BlockBot, but it would be amazing if at least the global chat from Carbon would be able to be recognised by BlockBot (https://github.com/DrexHD/BlockBot). I saw this mentioned on the discord before, hence the request. 

### Proposed Feature Functionality:

- Global chat being linked the the 'chat' channel of BlockBot
- ~~'Support for the 'bot.channels' of BlockBot to be linked to Carbon's channels~~ (just noticed the blockbot api only supports chat, console, alerts and log)

**Comment by VOrlando520** [comment]
I would like this request this as well!

**Comment by Draycia** [comment]
We've looked into BlockBot in the past and weren't too keen on supporting it. It only supports a single channel (global), and there's next to 0 documentation for how we should interface with it (tbf ours isn't the greatest either).

We are more than happy to support any alternatives for fabric that have channels, or revisit BlockBot if it gains support for them.

**Comment by Rozbiynk** [comment]
hi, I hope this will be helpful, but here is mod, that also use radius feature and has integration with blockbot https://github.com/ForwarD-NerN/SimpleChat/commit/771e9cfb91fa348cb61de6064f169a44b8b7f3b5. This exact commit bring it

**Comment by SerpentesNL** [comment]
We have switched to having Carbon plus CarbonVelocityDiscord instead of trying to run it on fabric, so this request is no longer relevant to me.

**Comment by Rozbiynk** [comment]
> We have switched to having Carbon plus CarbonVelocityDiscord instead of trying to run it on fabric, so this request is no longer relevant to me.

can you please give link to carbonVelocityDiscord?

**Comment by SerpentesNL** [comment]
> > We have switched to having Carbon plus CarbonVelocityDiscord instead of trying to run it on fabric, so this request is no longer relevant to me.
> 
> can you please give link to carbonVelocityDiscord?

Had the name in a slightly different order, but here it is: 
https://github.com/Jarva/VelocityCarbonDiscord
https://modrinth.com/plugin/velocity-carbon-discord
