### ISSUE TITLE
[Bug] Chat works while u not login to server

### ISSUE THREAD

**Issue by SantaSpeen** [Draycia/Chat#383]
### Steps to reproduce:

1. AuthMe + Carbon

### System Details:

1. Server Type:          PurPur
2. Server Software:    2114
3. MC Version:           1.20.4
4. Carbon Version:   DevBuild (With psql) `carbonchat-paper-3.0.0-SNAPSHOT+3e87151.jar`

The chat works even when I'm not logged in..
![image](https://github.com/Hexaoxide/Carbon/assets/68832064/a6325b25-7a38-4166-bb79-a9979f41c771)

**Comment by jpenilla** [comment]
Please let us know if you can reproduce this issue without AuthMe. If not, it's an AuthMe problem and should be reported to the devs of that plugin.
