### ISSUE TITLE
[Bug]  Plugin Crush

### ISSUE THREAD

**Issue by ProffFate** [Draycia/Chat#385]
[crash-2024-01-07_12.49.03-server.txt](https://github.com/Hexaoxide/Carbon/files/13853532/crash-2024-01-07_12.49.03-server.txt)

I connect to RABBITMQ and my server won't start, carbon chat plugin crush with error, error details in attachment

**Comment by jpenilla** [comment]
Crash reports are generally kind of useless, we would need to see the entire log to say anything. https://mclo.gs

**Comment by jpenilla** [comment]
Closing due to lack of response
