### ISSUE TITLE
[Feature] Option to reverse parameters passed to PlaceholderAPI on relational placeholders

### ISSUE THREAD

**Issue by Kamilkime** [Draycia/Chat#445]
### Proposed Feature Description:

Currently the relational placeholders for PlaceholderAPI are used [like this](https://github.com/Hexaoxide/Carbon/blob/65a3152d03844ea83463bd7655d1df66ea5c39f9/paper/src/main/java/net/draycia/carbon/paper/messages/PaperMessageRenderer.java#L131). The sender player is the first parameter, and the receiving player is the second.

However, PlaceholderAPI does not specify which parameter means what. To be honest I've more plugins doing this the opposite way - treating the first parameter as the observer, and the second as the message sender. For example when implementing [this](https://github.com/FunnyGuilds/FunnyGuilds/blob/336b3659e3268db3e863c5413aa987679b893d00/plugin/src/main/java/net/dzikoysk/funnyguilds/feature/hooks/placeholderapi/PlaceholderAPIHook.java#L80) we've assumed just that and tested it with a couple other plugin (e.g. TAB).

My proposal would be to add an option, which would allow the user to switch the order of the variables. If possible - maybe even somehow do that per placeholder, which is actually substituted? I think it would be one of the only (or even **the** only) plugin which would allow such a choice.

### Proposed Feature Functionality:

Possibly a config option, allowing the possibility to switch the order of the passed Player variables.

**Comment by Draycia** [comment]
Fixed in af12f92650de92caa704be39bb10b28df97ac46b
It makes more sense for the recipient to be the first parameter, as you're parsing placeholders for that player.
