### ISSUE TITLE
[Bug] Clear chat does not clear chat

### ISSUE THREAD

**Issue by BurkenDev** [Draycia/Chat#448]
When running the /clearchat command it just broadcast the configured message.
The message set to "" by default never displays in the chat, nor does it display anything in chat if you change the message to like "aa" or something. It just states chat was cleared and I still see what was before this message.

**Comment by Draycia** [comment]
Unable to reproduce, if I negate the `carbon.clearchat.exempt` permission or don't give myself the permission, the blank message is sent and chat is cleared.
