### ISSUE TITLE
[Bug] Color codes does not translate properly.

### ISSUE THREAD

**Issue by BurkenDev** [Draycia/Chat#450]
It seems like standard minecraft color codes aren't parsed properly. For example if I type &6 before my chat text, it should have the same behaviour as the miniformat <gold>.

**Comment by NamiUni** [comment]
Conditions for using legacy color codes
1. CarbonChat is installed on a backend server such as Paper.
2. PlaceholderAPI is installed.
3. The sender of the chat has the permission `carbon.chatplaceholders`.

Or, set up a chat filter from config and give the player the permission `carbon.messagetags.color`.
```hocon
chat-filter {
    "&6"="<gold>"
}
```

@Draycia 
Is there any reason why legacy color codes can only be used when PAPI is installed?
https://github.com/Hexaoxide/Carbon/blob/trunk/paper/src/main/java/net/draycia/carbon/paper/hooks/PAPIChatHook.java

**Comment by jpenilla** [comment]
The only place legacy is supported in any capacity by Carbon is as the result of a PAPI placeholder. Anywhere else it works is a bug.
