### ISSUE TITLE
[Bug] The smg have some bugs

### ISSUE THREAD

**Issue by liannai569** [Draycia/Chat#451]
https://github.com/Hexaoxide/Carbon/assets/89626087/7f27e304-f213-4a82-ba9f-f6b7d528f99b

I have tow account one is Liannai other is Liannai1 , Liannai can msg Liannai1 but Liannai1 can't msg Liannai
And is it possible to add a private chat channel? It would be very troublesome for players to frequently use /msg ID.

Server Type: Bukkit
Server Software: Current: git-Purpur-2155 (MC: 1.20.4)*
MC Version: 1.20.4
Carbon Version: 3.0-Beta26
redis version: 5.0.14

**Comment by jpenilla** [comment]
Are you in offline mode? I can't reproduce any issues whispering between two players on the same server or cross-server. We would need reproduction steps to look into this further.
