### ISSUE TITLE
[Bug] Permission "carbon.channel.<channel>.speak" is never checked

### ISSUE THREAD

**Issue by OfficialTheosis** [Draycia/Chat#466]
## Bug Description:
Title says it all.
### What is not working as it should?
Title says it all.
### Steps to reproduce:

1. Install Carbon, Vault, and LuckPerms
2. Log in, talk in a channel that you do not have the `carbon.channel.<channel>.speak` permission for, and you will see that you can send messages in that channel (make sure you have  `carbon.channel.<channel>.see` in order to see the message).
3. Use `/lp verbose on carbon` to see which permissions are being checked, and you will see that `carbon.channel.<channel>.speak` is not checked upon sending chat messages.
-->

### System Details:

1. Server Type:          Bukkit
2. Server Software:    Paper-493
4. MC Version:           1.20.4
5. Carbon Version:     carbonchat-paper-3.0.0-beta.26

**Comment by Loapu** [comment]
It seems like this permission is only checked, when the player tries to join a channel.
