### ISSUE TITLE
[Feature] Let me block non-alphanumeric characters from /nick

### ISSUE THREAD

**Issue by ZepsiZola** [Draycia/Chat#501]
### Proposed Feature Description:

Currently players are able to add any characters into their nick. I want to restrict the allowed characters to just `AbBbCc...`, `123...`, and `_` and thats it.

### Proposed Feature Functionality:

Just have a boolean in the config.yml that says `NonAlphanumericInNickname:` and I can set that to `true` or `false`.

**Comment by jpenilla** [comment]
#485
