### ISSUE TITLE
[Bug] I cannot put two variables together.

### ISSUE THREAD

**Issue by ChrisTVH** [Draycia/Chat#502]
Good to all, I have a problem is that I want to color the formats with chatcolor, but there is a space when I do it in the format and if I paste it gives error.

Edit: This only happens if the variable is empty, I just realized that fact.

### If I use it this way it does not give an error, but it leaves an extra space.
```conf
default="%cc_full_color% %luckperms_prefix% %carbonchat_nickname% <#454545>»<reset>%cc_full_color% <message>"
```
### If I use it this way it gives a critical error and restarts the server.
```conf
default="%cc_full_color%%luckperms_prefix% %carbonchat_nickname% <#454545>»<reset>%cc_full_color% <message>"
```
Versions:
git-Purpur-2175 (MC: 1.20.4)*
CarbonChat v3.0.0-beta.26

**Comment by jpenilla** [comment]
you need to provide the actual error as outlined in the issue template

**Comment by ChrisTVH** [comment]
> you need to provide the actual error as outlined in the issue template

Here is the link to the log:
https://mclo.gs/D6KXEns

**Comment by jpenilla** [comment]
Are you sure that is the correct log, it just looks like you have an issue with your RMQ server/configuration.

**Comment by ChrisTVH** [comment]
> Are you sure that is the correct log, it just looks like you have an issue with your RMQ server/configuration.

Sorry, that's the wrong log.
https://mclo.gs/MxIZPi4

**Comment by jpenilla** [comment]
This should be reported to the developer of `com.sulphate.chatcolor2.utils.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:94) ~[ChatColor2-1.14.3.jar:?]`
