### ISSUE TITLE
[Feature] More customization in nicknames

### ISSUE THREAD

**Issue by ChrisTVH** [Draycia/Chat#503]
### Proposed Feature Description:

In short I want to customize how the nicknames are displayed in the tab, it always appears with plain text and in everything I have checked I can't change it.
![image](https://github.com/Hexaoxide/Carbon/assets/58376852/7bc0cb8f-1d85-43a4-a4fd-f9fa855402ce)

### Proposed Feature Functionality:

In the nicknames section you should be able to configure it with the minimessages or an option to disable the nicks in the tab so that I can implement it using the variables.

**Comment by jpenilla** [comment]
See #471 and #488

**Comment by ChrisTVH** [comment]
> See #471 and #488

Wow how quick you are to answer, is there already a build with this feature available?

**Comment by jpenilla** [comment]
You can use the latest GH actions artifact from the `trunk` branch or the 1.21 PR for MC 1.21.

**Comment by ChrisTVH** [comment]
> You can use the latest GH actions artifact from the `trunk` branch or the 1.21 PR for MC 1.21.

I tried it in 1.20.4 as my server is of that version and the format did not load....
And I can not migrate to 1.21 many bugs.
