### ISSUE TITLE
[Bug] "Exceeded character limit" broken.

### ISSUE THREAD

**Issue by ZepsiZola** [Draycia/Chat#504]
### What is not working as it should?

Plugin says the nickname exceeds character limit when it should not.

![image](https://github.com/Hexaoxide/Carbon/assets/49735083/89859d8e-4e65-43a9-9f0f-7f3a90cc3ce2)

### Steps to reproduce:

1. Install Carbon, Vault, and LuckPerms
2. Give non-op player `carbonchat.nickname.set`, `carbon.nickname.tags.color`, `carbon.nickname.tags.gradient`
3. Have player type the command `/nick<gradient:000000:FFFFFF>TestName`
4. Plugin says that the name exceeds the character limit.

### System Details:

1. Server Type: Folia         
2. Server Software: Folia version git-Folia-"ef2c697" (MC: 1.20.4)   
3. MC Version: 1.206          
4. Carbon Version: 3.0.0-SNAPSHOT+4670b57

**Comment by jpenilla** [comment]
The provided nickname is not valid MiniMessage. So the entire content has its length checked. If the gradient tag was valid only "TestName" would count.

See https://webui.advntr.dev/, https://docs.advntr.dev/minimessage/

![Screenshot 2024-06-22 at 5 08 27 PM](https://github.com/Hexaoxide/Carbon/assets/11360596/568c9f3f-06f5-4248-82a0-9d6a34937fa0)
