### ISSUE TITLE
Strange characters [Bug]

### ISSUE THREAD

**Issue by ChrisTVH** [Draycia/Chat#506]
## Bug Description:

It happens that since I started using carbon chat, sometimes in rare cases I get kicked out of the server, saying that it could not verify the chat message.
Well I have disabled that in server.propierties, and I don't use signeyvelocity either because I have non-premium and premium players.
Well when that happens I get some weird characters.
![image](https://github.com/Hexaoxide/Carbon/assets/58376852/355230b9-185a-4057-b993-3d6b6a4c362e)

I also suspect that these characters are related to this error I am getting in the proxy:
![image](https://github.com/Hexaoxide/Carbon/assets/58376852/8d9e5b3f-3fc7-4cdc-82ee-1f335927a230)

### Steps to reproduce:

I use chatcolor2 together with carbon chat, although the only thing chatcolor2 does is to set colors with a variable.
Otherwise, it just happens, actually I have disabled anything that interferes with the chat.
Also, this started to appear when I started using carbon chat.

### System Details:

1. Server Type:          Velocity, Paper (Carbon is only in the backends)
2. Server Software:    git-Purpur-2175 (MC: 1.20.4)*Previous: git-Purpur-2174 (MC: 1.20.4)*
3. MC Version:           1.20.4
4. Carbon Version: [#2800](https://github.com/Hexaoxide/Carbon/actions/runs/9669759756)

### Pastebins:

![image](https://github.com/Hexaoxide/Carbon/assets/58376852/cef23617-a219-4521-ba9d-3fe14d7743c6)

**Comment by jpenilla** [comment]
Carbon doesn't use teams at all and is not in the provided stacktrace, I'm not sure there is actually a Carbon issue here.

**Comment by ChrisTVH** [comment]
> Carbon doesn't use teams at all and is not in the provided stacktrace, I'm not sure there is actually a Carbon issue here.

I'm going to do some discard tests just in case to see.
I will comment later, that would be tomorrow afternoon.
