### ISSUE TITLE
Conflict with a moderation plugin [Bug]

### ISSUE THREAD

**Issue by ChrisTVH** [Draycia/Chat#509]
## Bug Description:

It's an occasional error that comes up sometimes, it happens when you run a carbon command, I think it started since I added chat sentinel, so it could be a conflict issue with each other.

![image](https://github.com/Hexaoxide/Carbon/assets/58376852/674929b0-8520-49c5-bcdf-e8b32cd19ac8)

### Steps to reproduce:

1. Install carbon together with chat sentinel.
2. In chat sentinel, enable the option to censor bad words, change uppercase to lowercase and/or remove repeated characters.

Well basically any option that modifies the message before it is sent with carbon chat.

### System Details:

1. Server Type:          Paper -> Pufferfish -> Purpur
3. Server Software:    git-Purpur-2175 (MC: 1.20.4)
4. MC Version:           1.19.4 – 1.21
5. Carbon Version: carbonchat-paper-3.0.0-SNAPSHOT+3a93b78 I think it was: [#2800](https://github.com/Hexaoxide/Carbon/actions/runs/9669759756)

### Pastebins:

https://mclo.gs/oix7mTQ

**Comment by jpenilla** [comment]
Please open a new issue if this happens on Paper with no other plugins. It looks like some other plugin is either mangling the command tree before it's sent to the client or improperly intercepting the command packet somehow.
