### ISSUE TITLE
[Bug] Error initializing plugin

### ISSUE THREAD

**Issue by cgw2023** [Draycia/Chat#514]
## Bug Description:
Carbon cannot be enabled 

### What is not working as it should?

The plugin itself

### Steps to reproduce:

1. Install Carbon on folia

### System Details:

1. Server Type:          Folia
2. Server Software:   folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
3. MC Version:          1.20.4
4. Carbon Version:  carbonchat-paper-3.0.0-beta.27

### Pastebins:

https://paste.denizenscript.com/View/124634

### Any other relevant details:

no

**Comment by jpenilla** [comment]
Beta 27 was incorrectly marked as being compatible with 1.20.4, but it's actually 1.20.6+. Will be fixed in next beta.
