### ISSUE TITLE
Vanilla commands are not replaced by carbon commands in 1.21 [Bug]

### ISSUE THREAD

**Issue by ChrisTVH** [Draycia/Chat#515]
### When using: /tell, /msg or /w
It does not use carbon chat to send the private message but the vanilla command.
![image](https://github.com/user-attachments/assets/ddfe9d40-2a9a-4d00-8a02-0f2a8ccd1cc0)
![image](https://github.com/user-attachments/assets/0695e0d4-408e-4d3a-992f-9132a14a70ca)

### The expected result is:
![image](https://github.com/user-attachments/assets/ec00bbf3-5fcf-43f3-afb2-21691c49b5e0)

### System Details:

1. Server Type: Paper
2. Server Software: Current Purpur Version: 1.21-2275-82ccc76 (MC: 1.21)*
3. MC Version: 1.19.4 - 1.21
4. Carbon Version: [3.0.0-SNAPSHOT+bf82dc8](https://github.com/Hexaoxide/Carbon/actions/runs/10115494812)

### Any other relevant details:

Default configuration of carbon chat, with respect to the above-mentioned commands.
![image](https://github.com/user-attachments/assets/ec455bc8-86b5-4f1d-b71c-fc30c74bbe29)
It is possible that if there are other commands that replace the vanilla ones, they may not work either, I have only tried the ones mentioned in this issue.

**Comment by NamiUni** [comment]
Paper bug
https://github.com/PaperMC/Paper/issues/11035#issuecomment-2252012274
