### ISSUE TITLE
[Bug] Unable to load plugin

### ISSUE THREAD

**Issue by xiaozhangup** [Draycia/Chat#532]
## Bug Description:
Unable to load plugin
### What is not working as it should?
There seems to be an error encountered when loading the dependency as follows
https://mclo.gs/K8NbROC
### Steps to reproduce:
Install carbonchat-paper-3.0.0-beta.27 to paper server

### System Details:

1. Server Type:          Paper Fork (My custom fork)
2. Server Software:    Paper
3. MC Version:           1.20.4
4. Carbon Version: carbonchat-paper-3.0.0-beta.27

### Pastebins:

https://mclo.gs/K8NbROC

**Comment by xiaozhangup** [comment]
And the version of carbonchat-paper-3.0.0-beta.26 work fine for me

**Comment by broccolai** [comment]
the .27 release is labled wrong, it only supports .6 and higher you'll have to stay on the older version or update the server
