### ISSUE TITLE
[Bug] Chat messages show the receiver's prefixes/suffixes for all messages

### ISSUE THREAD

**Issue by JasonHorkles** [Draycia/Chat#534]
## Bug Description:
The plugin shows each person's chat message with the receiver's own prefixes and suffixes, rather than the sender's
### What is not working as it should?
The prefix and suffix placeholders with MiniPlaceholders
### Steps to reproduce:
1. Install Carbon, SignedVelocity if needed, LuckPerms, MiniPlaceholders, and MiniPlaceholders LP Expansion on Velocity
2. Add the MP prefix and suffix placeholders to the chat format
3. Have 2 users join
4. Assign a prefix and suffix to only 1 user
5. Send a message, and see that it's different depending on the person receiving it

### System Details:

1. Server Type:          Proxy
2. Server Software:    Velocity 3.3.0 git-6100e675-b416
3. MC Version:           1.21.1
4. Carbon Version:     3.0.0-beta27

### Pastebins:

The only thing relevant is the chat format, of which mine can be used:
```
console="<dark_aqua>GLOBAL<reset> <dark_gray>><reset> <display_name><dark_aqua> | <luckperms_suffix><message>"
"default_format"="<luckperms_prefix><dark_aqua>◀<reset> <click:suggest_command:/tell <username> ><display_name></click><dark_aqua> ▶<reset> <luckperms_suffix><message>"
```

### Any other relevant details:
This does not happen on beta build 26. It also displays fine in console on 27.

| Main Account | Alt Account |
| - | - |
![image](https://github.com/user-attachments/assets/27532894-2835-4454-8169-886fa9fea750) | ![image](https://github.com/user-attachments/assets/c1d67eb7-a06d-49f9-b6e2-c3ffc6788f3a)

**Comment by KingJorjai** [comment]
Currently having the same issue while using **Carbon** with **MiniPlaceholders** and **MiniPlaceholders LP Expansion**.
## System details
1. Server type: **Proxy**
2. Server Software: **Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)**
3. MC version: **1.21.1**
4. Carbon version: **3.0.0-beta.27**
## Additional information 
In addition to what @JasonHorkles stated, I have realised that the placeholder works as expected (showing the sender's prefix) when sent in a message.

**Comment by Draycia** [comment]
Caused by `getRelationalGlobalPlaceholders` being used instead of `getRelationalPlaceholders` on the Velocity module, overriding the sender's placeholders with the recipient's. Fixed in the next dev build(s).
