### ISSUE TITLE
[Bug] PAPI Placeholders in chat format not working

### ISSUE THREAD

**Issue by rowdyslav** [Draycia/Chat#540]
## Bug Description:

PAPI Placeholders in global chat format not working

### What is not working as it should?
Placeholders in chat format

### Steps to reproduce:

1. Install Carbon
2. Send message to single global chat

### System Details:

1. Server Type:          Proxy
2. Server Software:    Latest Velocity
3. MC Version:          1.21.1
4. Carbon Version:    3.0.0 beta 27

### Pastebins:

`[02:30:32 INFO]: [carbon:global] %vault_prefix&r rowdyslav: re
`

**Comment by jpenilla** [comment]
PlaceholderAPI does not exist on the proxy. MiniPlaceholders does, see https://github.com/MiniPlaceholders/PlaceholderAPI-Expansion
