### ISSUE TITLE
[Bug] Dev Branch (SocialSpy Addition)

### ISSUE THREAD

**Issue by ColdSight** [Draycia/Chat#547]
## Bug Description:
1. Radius spy messages weren't added to locale

### What is not working as it should?
1. Radius spy messages aren't added to locale (unless manually added to locale) 

### Steps to reproduce:

1. Install Carbon, Vault, and LuckPerms
2. Locale will not generate the radius spy message

### System Details:

Running Pufferfish on 1.21.1 using the most up to date carbon dev build

### Pastebins:
When /spy is enabled:
![image](https://github.com/user-attachments/assets/464acd6f-33f7-4e96-af2a-8ba328139cdf)

**Comment by JosTheDude** [comment]
You have a `/spy` command? What's the permission -- I have Carbon installed but don't have it
