### ISSUE TITLE
[Bug] `carbon.spy` Permission does not Work

### ISSUE THREAD

**Issue by JosTheDude** [Draycia/Chat#575]
## Bug Description
When a player has `carbon.spy`, it does not show any private messages or radius-based chats despite the permission stating this is what it does.

### What is not working as it should?
How `carbon.spy` works

### Steps to reproduce:

1. Install Carbon, Vault, and LuckPerms
2. Create a channel with a radius limit (i.e. 50 blocks)
3. Give a player `carbon.spy`
4. Player with `carbon.spy` cannot view chat messages of player in radius (or messages)

### System Details:

1. Server Type:         Pufferfish (bukkit)
2. Server Software:    1.21.1-21-HEAD@cfa3c61 (2024-10-22T23:08:19Z)
5. MC Version:           1.21.1
6. Carbon Version: 3.0.0 (beta-27)

### Pastebins:
N/A
### Any other relevant details:

I believe that Carbon should mirror other chat plugins and implement a `/socialspy` command to view private messages as well as `/radiusspy` to spy on local messages over the permission system currently.

**Comment by Draycia** [comment]
The `carbon.spy` permission is used for the `/spy` command, which works on radius, whisper, party, and muted player chat attempts.

Edit: Updated docs to make this more clear.
